### ISSUE TITLE
Using `GeneratorOptions.FlatPackage` results in generated code that won't compile

### ISSUE THREAD

**Issue by plaflamme** [scalapb/scalapb-validate#17]
I'm not sure how to make an actual test for this, so here's a demonstration using the `example` project https://github.com/plaflamme/scalapb-validate/commit/76e3ec7d0cc53743b60ae9a8e26285728953b284

The resulting code will be generated like so:

```scala
object Proto3Proto extends _root_.scalapb.GeneratedFileObject {

  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    com.google.protobuf.wrappers.WrappersProto,
    io.envoyproxy.pgv.validate.ValidateProto
  )
...
}
```

But `io.envoyproxy.pgv.validate.ValidateProto` should actually be `io.envoyproxy.pgv.validate.validate.ValidateProto`

This might be an issue in `ScalaPb`? I'm not quite sure how it handles this case for google's well known types for example.

**Comment by plaflamme** [comment]
FYI: I'm happy to help fix this with some guidance...

**Comment by thesamet** [comment]
When you pass flatPackage (or any other setting) to the generator, the generator applies it to all proto files, including those imported. The solution would be to apply flatPackage only to your package by using package-scoped options: https://scalapb.github.io/customizations.html#package-scoped-options.

The reason things work when you import google/protobuf/*.proto and scalapb.proto is due to [this hack](https://github.com/scalapb/ScalaPB/blob/da9476039b61a32592d67c1e15b5ecc6d7eeb38d/compiler-plugin/src/main/scala/scalapb/compiler/DescriptorImplicits.scala#L881-L882), so a possible fix would be to add "validate" to the list, but I'd rather not start building in ScalaPB core a list of third-party or experimental code that was compiled with standard settings.

**Comment by plaflamme** [comment]
Ok, thanks, that's the hack I failed to find. Makes sense.

Perhaps `GeneratorOption.FlatPackage` should be deprecated in favour of the using package-scoped option?

**Comment by thesamet** [comment]
Agree, would be nice to deprecate it in favor of package-scoped options. I thought to also provide a way to scope FlatPackage to a package through a parameter, to make it easier for users.
